name: SDP tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements.txt
        apt-get update && apt-get install -y libsndfile1 ffmpeg
        pip install Cython
        pip install "nemo_toolkit[asr,nemo_text_processing]"
    - name: Run all tests
      run: |
        pytest --durations=30 -rs
